name: Test
run-name: "Acceptance Test — ${{ github.ref_name }}"

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Lint
        uses: golangci/golangci-lint-action@v9.2.0

  acceptance-test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_wrapper: false

      - name: Run acceptance tests
        run: go test ./internal/provider/ -v -timeout 120m
        env:
          TEST_DVLS_APP_ID: ${{ secrets.TEST_DVLS_APP_ID }}
          TEST_DVLS_APP_SECRET: ${{ secrets.TEST_DVLS_APP_SECRET }}
          TEST_DVLS_BASE_URI: ${{ secrets.TEST_DVLS_BASE_URI }}
          TF_ACC: "1"
